trigger: none

parameters:
  - name: JSON_FILENAME
    type: string

jobs:
  - job: Container
    pool: 'Coles-Private-Hosted-Store-Team-NonProd-Scalable'
    #container: cached-images.azr.cmltd.net.au/powershell-pipeline:latest
    steps:
      - checkout: self
        fetchDepth: 1
        persistCredentials: true

      - task: Bash@3
        displayName: Apply branch protection rules in the json file 
        env:
          GITHUB_PAT: $(GITHUB_PAT)
        inputs:
          targetType: 'inline'
          script: |
            ls
            JSON_FILENAME=${{ parameters.JSON_FILENAME }}
            # get URL
            URL=$(cat $JSON_FILENAME | jq '.url')
            curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $(GITHUB_PAT)" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$URL" \
            -d '{"required_status_checks":{"url":"https://api.github.com/repos/Coles-Store-Team-Platform/kleene-cli/branches/main/protection/required_status_checks","strict":true,"contexts":["Kleene Build"],"contexts_url":"https://api.github.com/repos/Coles-Store-Team-Platform/kleene-cli/branches/main/protection/required_status_checks/contexts","checks":[{"context":"Kleene Build","app_id":9426}]},"required_pull_request_reviews":{"url":"https://api.github.com/repos/Coles-Store-Team-Platform/kleene-cli/branches/main/protection/required_pull_request_reviews","dismiss_stale_reviews":true,"require_code_owner_reviews":true,"require_last_push_approval":false,"required_approving_review_count":1},"required_signatures":{"url":"https://api.github.com/repos/Coles-Store-Team-Platform/kleene-cli/branches/main/protection/required_signatures","enabled":false},"enforce_admins":{"url":"https://api.github.com/repos/Coles-Store-Team-Platform/kleene-cli/branches/main/protection/enforce_admins","enabled":false},"required_linear_history":{"enabled":false},"allow_force_pushes":{"enabled":false},"allow_deletions":{"enabled":false},"block_creations":{"enabled":false},"required_conversation_resolution":{"enabled":false},"lock_branch":{"enabled":false},"allow_fork_syncing":{"enabled":false}}'