trigger: none

parameters:
  - name: JSON_FILENAME
    type: string

jobs:
  - job: Container
    pool: 'Coles-Private-Hosted-Store-Team-NonProd-Scalable'
    #container: cached-images.azr.cmltd.net.au/powershell-pipeline:latest
    steps:
      - checkout: self
        fetchDepth: 1
        persistCredentials: true

      - task: Bash@3
        displayName: Apply branch protection rules in the json file 
        env:
          GITHUB_PAT: $(GITHUB_PAT)
        inputs:
          targetType: 'inline'
          script: |
            ls
            JSON_FILENAME=${{ parameters.JSON_FILENAME }}
            # get URL
            URL=$(cat $JSON_FILENAME | jq '.url' | tr -d '"')
            echo $URL
            curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $(GITHUB_PAT)" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            $URL \
            -d $(jq -c . $JSON_FILENAME)