parameters:
  - name: REPO_OWNER_REPO_NAME
    type: string
    default: "Coles-Store-Team-Platform/kleene-cli"

jobs:
  - job: Container
    pool: 'Coles-Private-Hosted-Store-Team-NonProd-Scalable'
    #container: cached-images.azr.cmltd.net.au/powershell-pipeline:latest
    steps:
      - checkout: self
        fetchDepth: 1
        persistCredentials: true

      - task: Bash@3
        displayName: Generate repos config json files
        #condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        env:
          GITHUB_PAT: $(GITHUB_PAT)
        inputs:
          targetType: 'inline'
          script: |
            IFS=/
            REPO_OWNER_REPO_NAME=${{ parameters.REPO_OWNER_REPO_NAME }}
            set $REPO_OWNER_REPO_NAME
            REPO_OWNER=$1
            REPO_NAME=$2
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $(GITHUB_PAT)" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/branches/main/protection -o $REPO_OWNER_$REPO_NAME_main.json
            
            cat $REPO_OWNER_$REPO_NAME_main.json